"""Recipe

Revision ID: 32856ac47021
Revises: 8548b9ce65f7
Create Date: 2024-07-01 19:57:46.635617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32856ac47021'
down_revision: Union[str, None] = '8548b9ce65f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Recipe_Ingredient',
    sa.Column('id_Dish', sa.UUID(), nullable=False),
    sa.Column('id_Ingredient', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Dish'], ['Dish.id'], ),
    sa.ForeignKeyConstraint(['id_Ingredient'], ['Ingredient.id'], ),
    sa.PrimaryKeyConstraint('id_Dish', 'id_Ingredient')
    )
    op.add_column('Dish', sa.Column('instructuions', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dish', 'instructuions')
    op.drop_table('Recipe_Ingredient')
    # ### end Alembic commands ###
