"""Recipe fix

Revision ID: 4e8bc723557a
Revises: 32856ac47021
Create Date: 2024-07-01 19:59:10.390695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8bc723557a'
down_revision: Union[str, None] = '32856ac47021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dish', sa.Column('instructions', sa.String(length=1000), nullable=True))
    op.drop_column('Dish', 'instructuions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dish', sa.Column('instructuions', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('Dish', 'instructions')
    # ### end Alembic commands ###
