"""Menu

Revision ID: d36e10d6d57e
Revises: 4e8bc723557a
Create Date: 2024-07-02 23:42:01.509399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36e10d6d57e'
down_revision: Union[str, None] = '4e8bc723557a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Menu',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Menu_Dishes',
    sa.Column('id_Dish', sa.UUID(), nullable=False),
    sa.Column('id_Menu', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_Dish'], ['Dish.id'], ),
    sa.ForeignKeyConstraint(['id_Menu'], ['Menu.id'], ),
    sa.PrimaryKeyConstraint('id_Dish', 'id_Menu')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Menu_Dishes')
    op.drop_table('Menu')
    # ### end Alembic commands ###
